### ISSUE TITLE
First time user object disclaimer

### ISSUE THREAD

**Issue by Thagana** [A-Tokyo/react-apple-signin-auth#36]
Hello

Thank you for this library it helped a lot. but when i was using it i had no idea that second time sign in will not return a user object.

would it be possible to have a small disclaimer to people who are new to apple signin auth and are using the library to know that bit of information?

**Comment by A-Tokyo** [comment]
@Thagana Sounds like a great idea! ( : Would you be willing to contribute a PR? ✨

**Comment by A-Tokyo** [comment]
https://github.com/A-Tokyo/react-apple-signin-auth/pull/37
