### ISSUE TITLE
using usePopup=true results in the loss of the request settings

### ISSUE THREAD

**Issue by makeoverweb** [A-Tokyo/react-apple-signin-auth#59]
Hello, tell me why when using usePopup in the request parameters on https://appleid.apple.com/appleauth/auth/oauth/authorize is form_post replaced by web_message?And the scope is also lost.And if you specify usePopup=false, then everything is fine.
But this is inconvenient, I would like to perform authorization using usePopup.

**Comment by A-Tokyo** [comment]
Hey @makeoverweb This is a limitation by Apple SDK itself, not this library.

Is there a way I can help you?

**Comment by A-Tokyo** [comment]
@makeoverweb I think you can make use of the `state` param to retain some data upon successful redirection
