### ISSUE TITLE
Popup only working on https URLs

### ISSUE THREAD

**Issue by poeck** [a-tokyo/react-apple-signin-auth#83]
When using `popup: true`, the package seems to only work on https URLs.

Is there maybe a fix/workaround for this?

Otherwise I would maybe add a warning in the Readme. 😄

**Comment by a-tokyo** [comment]
Hey @poeck, 

As far as I know this is a limitation from Apple's side.  I tried finding a workaround when I first implemented this but ended up hitting a wall 😅

A README warning is a good idea.

**Comment by hkaya15** [comment]
if I use popup false, response is "Error: This action with HTTP POST is not supported by NextAuth.js" it doesn't work properly. But switch to true, it works well. 

Chatgpt says: "Apple's OAuth flow sometimes sends the callback as a POST request, especially when usePopup: false."

I am looking for fixing it with different approaches.

**Comment by a-tokyo** [comment]
As far as I know, this is a limitation from the Apple API.

**Comment by a-tokyo** [comment]
I think @lucascco's proposal should solve this issue, please feel free to reopen if you'd like to discuss further.
